---
title: "Lab 7: Stringr"
author: "Julianna Renzi"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Detect string patterns with `str_detect()`

```{r}
# create a toy vector
vec <- c("  A Unicorn   Fish", "add   cornmeal", "French fries", " acorn  SQUAsh")

# look for exact match
str_detect(vec, pattern = "corn") # looks for lowercase corn--returns TRUE/FALSE for each element
```

```{r}
# use starwars dataset
head(starwars)

walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk")) # note column you want

head(walk_subset)


# could also combo filter and str_detect using str_subset()
```
### Replace an existing string pattern with something else

```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")

vec_bren
```

Use with `mutate`

```{r}
# replace "Sky" with "TORNADO"
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))

head(sw_tornado)
```

### Deal with whitespaces 

```{r}
# str_trim removes excess leading and trailing white space
str_trim(vec)

# remove excess spaces between words as well as removing excess leading and trailing white space
str_squish(vec)
```

R is also case sensitive: sometimes need to update case: `str_to_*()`

```{r}
str_detect(vec, pattern = "Corn") # doesn't get anything

# change case
str_to_lower(vec) # very useful--more coder friendly and uniform

str_to_upper(vec)

str_to_title(vec) # each word is capitalized 
```

Using these in combination using piping

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))

sw_combo
```

